import type { Work, Route } from "@/types";

// 假数据：5 个地点 + 2 条路线，字段形状与真实 Supabase 完全一致
export const mockWorks: Work[] = [
  {
    id: "mock-tokyo",
    image_url: null,
    image_thumb: null,
    ai_country: "日本",
    ai_region: "关东",
    ai_city: "东京",
    ai_attraction: "东京铁塔",
    final_country: "日本",
    final_region: "关东",
    final_city: "东京",
    final_attraction: "东京铁塔",
    is_confirmed: true,
    lat: 35.6586,
    lng: 139.7454,
    opening_note: null,
    sort_order: 0,
    source_platform: "manual",
    notes: null,
    status: "been_there",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "mock-paris",
    image_url: null,
    image_thumb: null,
    ai_country: "法国",
    ai_region: "法兰西岛",
    ai_city: "巴黎",
    ai_attraction: "埃菲尔铁塔",
    final_country: "法国",
    final_region: "法兰西岛",
    final_city: "巴黎",
    final_attraction: "埃菲尔铁塔",
    is_confirmed: true,
    lat: 48.8584,
    lng: 2.2945,
    opening_note: null,
    sort_order: 1,
    source_platform: "manual",
    notes: null,
    status: "want_to_go",
    created_at: "2024-02-20T00:00:00Z",
    updated_at: "2024-02-20T00:00:00Z",
  },
  {
    id: "mock-beijing",
    image_url: null,
    image_thumb: null,
    ai_country: "中国",
    ai_region: "北京",
    ai_city: "北京",
    ai_attraction: "故宫",
    final_country: "中国",
    final_region: "北京",
    final_city: "北京",
    final_attraction: "故宫",
    is_confirmed: true,
    lat: 39.9163,
    lng: 116.3972,
    opening_note: null,
    sort_order: 2,
    source_platform: "manual",
    notes: null,
    status: "been_there",
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-03-10T00:00:00Z",
  },
  {
    id: "mock-nyc",
    image_url: null,
    image_thumb: null,
    ai_country: "美国",
    ai_region: "纽约州",
    ai_city: "纽约",
    ai_attraction: "自由女神像",
    final_country: "美国",
    final_region: "纽约州",
    final_city: "纽约",
    final_attraction: "自由女神像",
    is_confirmed: true,
    lat: 40.6892,
    lng: -74.0445,
    opening_note: null,
    sort_order: 3,
    source_platform: "manual",
    notes: null,
    status: "want_to_go",
    created_at: "2024-04-05T00:00:00Z",
    updated_at: "2024-04-05T00:00:00Z",
  },
  {
    id: "mock-sydney",
    image_url: null,
    image_thumb: null,
    ai_country: "澳大利亚",
    ai_region: "新南威尔士",
    ai_city: "悉尼",
    ai_attraction: "悉尼歌剧院",
    final_country: "澳大利亚",
    final_region: "新南威尔士",
    final_city: "悉尼",
    final_attraction: "悉尼歌剧院",
    is_confirmed: true,
    lat: -33.8568,
    lng: 151.2153,
    opening_note: null,
    sort_order: 4,
    source_platform: "manual",
    notes: null,
    status: "want_to_go",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-05-01T00:00:00Z",
  },
];

export const mockRoutes: Route[] = [
  {
    id: "route-asia",
    name: "亚洲行",
    color: "#60a5fa",
    created_at: "2024-01-01T00:00:00Z",
    items: [
      {
        id: "ri-tokyo",
        route_id: "route-asia",
        work_id: "mock-tokyo",
        sort_order: 0,
        work: mockWorks[0],
      },
      {
        id: "ri-beijing",
        route_id: "route-asia",
        work_id: "mock-beijing",
        sort_order: 1,
        work: mockWorks[2],
      },
    ],
  },
  {
    id: "route-west",
    name: "欧美行",
    color: "#f97316",
    created_at: "2024-02-01T00:00:00Z",
    items: [
      {
        id: "ri-paris",
        route_id: "route-west",
        work_id: "mock-paris",
        sort_order: 0,
        work: mockWorks[1],
      },
      {
        id: "ri-nyc",
        route_id: "route-west",
        work_id: "mock-nyc",
        sort_order: 1,
        work: mockWorks[3],
      },
      {
        id: "ri-sydney",
        route_id: "route-west",
        work_id: "mock-sydney",
        sort_order: 2,
        work: mockWorks[4],
      },
    ],
  },
];
