import type { ReplaySample } from "./types";

export const replaySamples: ReplaySample[] = [
  {
    id: "sample-01",
    title: "漓江峰林与游船",
    clueType: "landmark",
    decision: "confirm",
    imageSrc: "/portfolio/samples/sample-01.webp",
    imageAlt: "桂林漓江的喀斯特峰林、河流与游船",
    sourceNote: "Wikimedia Commons · shutterstuman · CC BY 2.0",
    ai: {
      country: "中国",
      region: "广西壮族自治区",
      city: "桂林市",
      attraction: "漓江风景区",
      confidence: "high",
      evidence: "图片展示了典型的喀斯特地貌，山峰林立，河流蜿蜒，多艘游船在河上行驶，这是桂林漓江的标志性景观。",
      lat: 25.2797,
      lng: 110.2843,
      openingNote: null,
    },
    verified: {
      country: "中国",
      region: "广西壮族自治区",
      city: "桂林市",
      attraction: "漓江风景名胜区",
    },
  },
  {
    id: "sample-02",
    title: "上海浦东天际线",
    clueType: "landmark",
    decision: "review",
    imageSrc: "/portfolio/samples/sample-02.webp",
    imageAlt: "黄浦江对岸的上海浦东陆家嘴天际线",
    sourceNote: "Wikimedia Commons · Stefan Fussan · CC BY-SA 3.0",
    ai: {
      country: "中国",
      region: "上海市",
      city: "上海市",
      attraction: "上海外滩",
      confidence: "high",
      evidence: "图片展示了上海著名的天际线，包括东方明珠塔和上海中心大厦等标志性建筑，这些位于黄浦江畔的地标性建筑是上海外滩的典型景观。",
      lat: 31.2304,
      lng: 121.4737,
      openingNote: null,
    },
    verified: {
      country: "中国",
      region: "上海市",
      city: "上海市",
      attraction: "浦东陆家嘴天际线",
    },
  },
  {
    id: "sample-03",
    title: "北京天坛祈年殿",
    clueType: "landmark",
    decision: "confirm",
    imageSrc: "/portfolio/samples/sample-03.webp",
    imageAlt: "北京天坛祈年殿及其前方广场",
    sourceNote: "Wikimedia Commons · Maros Mraz · CC BY-SA 3.0",
    ai: {
      country: "中国",
      region: "北京市",
      city: "北京市",
      attraction: "天坛",
      confidence: "high",
      evidence: "图片显示的是天坛，位于中国北京市，是著名的古代祭祀建筑群，具有独特的圆形三层屋顶和宽阔的广场。",
      lat: 39.8145,
      lng: 116.4572,
      openingNote: "天坛对公众开放，建议提前查看官方网站以获取最新的开放时间和门票信息。",
    },
    verified: {
      country: "中国",
      region: "北京市",
      city: "北京市",
      attraction: "天坛公园祈年殿",
    },
  },
  {
    id: "sample-04",
    title: "黄山云海与奇松",
    clueType: "landmark",
    decision: "review",
    imageSrc: "/portfolio/samples/sample-04.webp",
    imageAlt: "黄山的花岗岩山峰、奇松与云海",
    sourceNote: "Wikimedia Commons · Chi King · CC BY 2.0",
    ai: {
      country: "中国",
      region: "安徽省",
      city: null,
      attraction: "黄山",
      confidence: "high",
      evidence: "图片展示了典型的黄山地貌，包括奇松、怪石和云海，这些是黄山的标志性景观。",
      lat: 30.0187,
      lng: 118.1956,
      openingNote: null,
    },
    verified: {
      country: "中国",
      region: "安徽省",
      city: "黄山市",
      attraction: "黄山风景区",
    },
  },
  {
    id: "sample-05",
    title: "成都普通街道",
    clueType: "weak",
    decision: "manual",
    imageSrc: "/portfolio/samples/sample-05.webp",
    imageAlt: "成都 Shangye Street 的普通城市道路",
    sourceNote: "Wikimedia Commons · Daderot · CC0 1.0",
    ai: {
      country: "中国",
      region: "上海市",
      city: "上海市",
      attraction: null,
      confidence: "high",
      evidence: "街道两旁绿树成荫，车辆行驶，行人活动，具有典型的城市街道特征。",
      lat: 31.2304,
      lng: 121.4737,
      openingNote: null,
    },
    verified: {
      country: "中国",
      region: "四川省",
      city: "成都市",
      attraction: "Shangye Street",
    },
  },
  {
    id: "sample-06",
    title: "桂林中山中路街景",
    clueType: "weak",
    decision: "manual",
    imageSrc: "/portfolio/samples/sample-06.webp",
    imageAlt: "桂林中山中路的车辆、商铺与街道绿化",
    sourceNote: "Wikimedia Commons · Marco L · Public Domain",
    ai: {
      country: "中国",
      region: "广东省",
      city: "广州市",
      attraction: "北京路步行街",
      confidence: "high",
      evidence: "图片显示的是广州北京路步行街的景象，街道两旁有商铺和行人，左侧可见“老明记”等招牌，右侧有树木和电动车行驶。",
      lat: 23.1267,
      lng: 113.2804,
      openingNote: "北京路步行街为全天开放的商业步行街区。",
    },
    verified: {
      country: "中国",
      region: "广西壮族自治区",
      city: "桂林市",
      attraction: "中山中路",
    },
  },
];
